name := "illogical"
version := "0.1.0"
scalaVersion := "2.13.10"
libraryDependencies += "org.scalactic" %% "scalactic" % "3.2.14"
libraryDependencies += "org.scalatest" %% "scalatest" % "3.2.14" % "test"
